const MAP_DATA = {
  0: ['OOO', 'OOO', 'OOO', 'OOO'],
  1: ['OOO', 'OOX', 'XOO', 'OOO'],
  2: ['OOO', 'OOB', 'BBB', 'BOO'],
  3: ['OOO', 'OOO', 'OOX', 'XOO'],
  4: ['GGG', 'AOO', 'OOX', 'GGG'],
  5: ['GGG', 'GGG', 'XOO', 'OOA'],
  6: ['OOO', 'OOO', 'OOO', 'OOO'],
  7: ['OOX', 'GGG', 'XOO', 'OOO'],
  8: ['BBB', 'BBB', 'GGG', 'BBB'],
  9: ['XOO', 'OOO', 'OOX', 'GGG'],
  10: ['XOO', 'OOB', 'BBX', 'GGG'],
  11: ['OOX', 'GGG', 'XBB', 'BOO'],
  12: ['OOO', 'OOO', 'OOO', 'OOO'],
  13: ['OOX', 'XOO', 'OOO', 'OOO'],
  14: ['GGG', 'AOO', 'OOO', 'OOA'],
  15: ['XOO', 'OOO', 'OOO', 'OOX'],
  16: ['GGG', 'GGG', 'GGG', 'GGG'],
  17: ['GGG', 'GGG', 'GGG', 'GGG'],
  18: ['GGG', 'GGG', 'GGG', 'GGG'],
  19: ['XBB', 'BBB', 'GGG', 'GGG'],
  20: ['BBX', 'GGG', 'GGG', 'BBB'],
};
