const DUNGEON_DATA = {
  0: ['OOO', 'KKK', 'OOO', 'TTT'],
  1: ['OOO', 'OOB', 'COO', 'KKK'],
  2: ['OOO', 'OOB', 'BBB', 'BOO'],
  3: ['OOO', 'TTT', 'OOC', 'BOO'],
  4: ['UUU', 'AOO', 'OOC', 'LLL'],
  5: ['UUU', 'RRR', 'COO', 'OOA'],
  6: ['OOO', 'OOB', 'COO', 'KKK'],
  7: ['OOC', 'RRR', 'COO', 'KKK'],
  8: ['BBB', 'BBB', 'III', 'BBB'],
  9: ['COO', 'TTT', 'OOC', 'LLL'],
  10: ['COO', 'OOB', 'BBX', 'LLL'],
  11: ['OOC', 'RRR', 'XBB', 'BOO'],
  12: ['OOO', 'OOB', 'COO', 'KKK'],
  13: ['OOC', 'AOO', 'OOO', 'KKK'],
  14: ['UUU', 'AOO', 'OOO', 'OOA'],
  15: ['COO', 'TTT', 'OOO', 'OOA'],
  16: ['GGG', 'LLL', 'UUU', 'RRR'],
  17: ['GGG', 'LLL', 'UUU', 'RRR'],
  18: ['GGG', 'LLL', 'UUU', 'RRR'],
  19: ['XBB', 'BBB', 'III', 'LLL'],
  20: ['BBX', 'RRR', 'III', 'BBB'],
  21: ['III', 'LLL', 'GGG', 'RRR'],
};

const PAPER_DATA = {
  0: ['BOO', 'OOB', 'DDD', 'LLL'],
  1: ['OOB', 'RRR', 'DDD', 'BOO'],
  2: ['UUU', 'BOO', 'OOB', 'LLL'],
  3: ['UUU', 'RRR', 'BOO', 'OOB'],
  4: ['DDD', 'LLL', 'UUU', 'RRR'],
  5: ['UUU', 'AOO', 'DDD', 'OOA'],
  6: ['UUU', 'AOO', 'DDD', 'OOA'],
  7: ['DDD', 'LLL', 'UUU', 'RRR'],
  8: ['DDD', 'LLL', 'UUU', 'RRR'],
  9: ['DDD', 'LLL', 'UUU', 'RRR'],
  10: ['UUU', 'OOB', 'DDD', 'BOO'],
  11: ['BOO', 'RRR', 'OOB', 'LLL'],
  12: ['OOB', 'RRR', 'BOO', 'LLL'],
  13: ['UUU', 'BOO', 'DDD', 'OOB'],
};
