const ISLAND = {
  0: ['GGG', 'GGG', 'GGG', 'GGG'],
  1: ['BBB', 'BYG', 'GYB', 'BBB'],
  2: ['BBB', 'BYG', 'GGG', 'GYB'],
  3: ['BBB', 'BBB', 'BYG', 'GYB'],
  4: ['GGG', 'GYB', 'BYG', 'GGG'],
  5: ['GGG', 'GGG', 'GYB', 'BYG'],
  6: ['BBB', 'BBB', 'BBB', 'BBB'],
  7: ['GGG', 'GGG', 'GGG', 'GGG'],
  8: ['BYG', 'GGG', 'GYB', 'BBB'],
  9: ['GGG', 'GGG', 'GGG', 'GGG'],
  10: ['GYB', 'BBB', 'BYG', 'GGG'],
  11: ['GYB', 'BYG', 'GGG', 'GGG'],
  12: ['BYG', 'GGG', 'GGG', 'GYG'],
  13: ['GGG', 'GGG', 'GGG', 'GGG'],
  14: ['BYG', 'GYB', 'BBB', 'BBB'],
  15: ['GGG', 'GYB', 'BBB', 'BYG'],
  16: ['GYB', 'BBB', 'BBB', 'BYG'],
  17: ['BBB', 'BBB', 'BBB', 'BBB'],
  18: ['BBB', 'BBB', 'BBB', 'BBB'],
  19: ['GGG', 'GGG', 'GGG', 'GGG'],
  20: ['GGG', 'GGG', 'GGG', 'GGG'],
  21: ['GGG', 'GGG', 'GGG', 'GGG'],
  22: ['BBB', 'BBB', 'BBB', 'BBB'],
  23: ['BBB', 'BBB', 'BBB', 'BBB'],
  24: ['GGG', 'GGG', 'GGG', 'GGG'],
  25: ['GGG', 'GGG', 'GGG', 'GGG'],
  26: ['GGG', 'GRG', 'GRG', 'GGG'],
  27: ['GGG', 'GRG', 'GGG', 'GRG'],
  28: ['GGG', 'GGG', 'GRG', 'GRG'],
  29: ['GRG', 'GRG', 'GRG', 'GGG'],
  30: ['GRG', 'GGG', 'GRG', 'GRG'],
  31: ['GGG', 'GGG', 'GGG', 'GGG'],
  32: ['GRG', 'GGG', 'GRG', 'GGG'],
  33: ['GRG', 'GRG', 'GRG', 'GRG'],
  34: ['GRG', 'GGG', 'GRG', 'GGG'],
  35: ['GGG', 'GRG', 'GRG', 'GRG'],
  36: ['GRG', 'GRG', 'GGG', 'GRG'],
  37: ['GRG', 'GRG', 'GGG', 'GGG'],
  38: ['GGG', 'GRG', 'GGG', 'GRG'],
  39: ['GRG', 'GGG', 'GGG', 'GRG'],
  40: ['GGG', 'GGG', 'GRG', 'GGG'],
  41: ['GGG', 'GRG', 'GGG', 'GGG'],
  42: ['GRG', 'GGG', 'GGG', 'GGG'],
  43: ['GGG', 'GGG', 'GGG', 'GRG'],
};

const DUNGEON_TILES = {
  0: ['AAA', 'AAA', 'AAA', 'AAA'],
  1: ['AAA', 'AAH', 'VAA', 'AAA'],
  2: ['AAA', 'AAH', 'BBB', 'HAA'],
  3: ['AAA', 'AAA', 'AAV', 'HAA'],
  4: ['SSS', 'HAA', 'AAV', 'SSS'],
  5: ['SSS', 'SSS', 'VAA', 'AAH'],
  6: ['AAA', 'AAA', 'AAA', 'AAA'],
  7: ['AAV', 'SSS', 'VAA', 'AAA'],
  8: ['BBB', 'BBB', 'DDD', 'BBB'],
  9: ['VAA', 'AAA', 'AAV', 'SSS'],
  10: ['VAA', 'AAH', 'BBI', 'SSS'],
  11: ['AAV', 'SSS', 'IBB', 'HAA'],
  12: ['AAA', 'AAA', 'AAA', 'AAA'],
  13: ['AAV', 'HAA', 'AAA', 'AAA'],
  14: ['SSS', 'HAA', 'AAA', 'AAH'],
  15: ['VAA', 'AAA', 'AAA', 'AAH'],
  16: ['SSS', 'SSS', 'SSS', 'SSS'],
  17: ['SSS', 'SSS', 'SSS', 'SSS'],
  18: ['SSS', 'SSS', 'SSS', 'SSS'],
  19: ['IBB', 'BBB', 'DDD', 'SSS'],
  20: ['BBI', 'SSS', 'DDD', 'BBB'],
  21: ['DDD', 'SSS', 'SSS', 'SSS'],
};

const PAPER_DATA = {
  0: ['BOO', 'OOB', 'DDD', 'LLL'],
  1: ['OOB', 'RRR', 'DDD', 'BOO'],
  2: ['UUU', 'BOO', 'OOB', 'LLL'],
  3: ['UUU', 'RRR', 'BOO', 'OOB'],
  4: ['UUU', 'RRR', 'DDD', 'LLL'],
  5: ['UUU', 'BOO', 'DDD', 'OOB'],
  6: ['UUU', 'BOO', 'DDD', 'OOB'],
  7: ['UUU', 'RRR', 'DDD', 'LLL'],
  8: ['UUU', 'RRR', 'DDD', 'LLL'],
  9: ['DDD', 'LLL', 'UUU', 'RRR'],
  10: ['UUU', 'OOB', 'DDD', 'BOO'],
  11: ['BOO', 'RRR', 'OOB', 'LLL'],
  12: ['OOB', 'RRR', 'BOO', 'LLL'],
  13: ['UUU', 'BOO', 'DDD', 'OOB'],
};

const CURRENT_MAP = ISLAND;
